# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.2.0
_src_path: gh:epics-containers/ec-services-template
beamline: bl38p
cluster_name: k8s-p38
cluster_namespace: p38-iocs
cluster_type: dls_dedicated
description: beamline bl38p IOC Instances and Services
git_platform: github.com
github_org: epics-containers
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
repo_uri: git@github.com:epics-containers/bl38p.git
type: beamline
