# Pandablocks IOC image
image: ghcr.io/pandablocks/pandablocks-ioc:0.2.2b3
# this places the start.sh directly in the epics/ioc folder replacing where
# the framework usually looks for the global start.sh
iocConfig: /epics/ioc

# use p38detector account ID and group ID for access to /dls/p38/data
securityContext:
  runAsUser: 37143
  runAsGroup: 37143
